Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
analyze              1
clean                1
download_data        1
integration          1
total                5

Select jobs to execute...

[Fri May  9 16:37:41 2025]
rule download_data:
    output: datasets/cost-of-international-education/International_Education_Costs.csv, datasets/world-happiness/2019.csv
    jobid: 4
    reason: Missing output files: datasets/cost-of-international-education/International_Education_Costs.csv, datasets/world-happiness/2019.csv
    resources: tmpdir=C:\Users\ethan\AppData\Local\Temp

[Fri May  9 16:37:42 2025]
Error in rule download_data:
    jobid: 4
    output: datasets/cost-of-international-education/International_Education_Costs.csv, datasets/world-happiness/2019.csv

RuleException:
CalledProcessError in file C:\Users\ethan\OneDrive\Senior Year SEM 1\IS 477\is477-sp25-group48\Snakefile, line 11:
Command 'C:/Users/ethan/miniconda3/python.exe "C:\Users\ethan\OneDrive\Senior Year SEM 1\IS 477\is477-sp25-group48\.snakemake\scripts\tmp6ylqfvfq.download_data.py"' returned non-zero exit status 1.
  File "C:\Users\ethan\OneDrive\Senior Year SEM 1\IS 477\is477-sp25-group48\Snakefile", line 11, in __rule_download_data
  File "C:\Users\ethan\miniconda3\lib\concurrent\futures\thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
